version: '3.3'
volumes:
  data:
services:
  db:
    image: mysql:8.0.16
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=app_development
      - MYSQL_ALLOW_EMPTY_PASSWORD=mypassword 
      - MYSQL_RANDOM_ROOT_PASSWORD=mypassword

#services:
#  db:
#    image: mysql
#    command: mysqld --default-authentication-plugin=mysql_native_password
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example

